name: 🚨 Нарушение лицензии CC BY-NC-SA 4.0
description: Сообщить о коммерческом использовании материалов Legal Prompts Hub
title: "[НАРУШЕНИЕ] "
labels: ["violation", "review-needed"]
assignees:
  - appankratova

body:
  - type: markdown
    attributes:
      value: |
        ## 🛡️ Спасибо за защиту открытого знания!
        
        Вы помогаете Legal Prompts Hub оставаться честным проектом.
        
        **⚠️ Важно:** Мы гарантируем **полную анонимность** заявителя.
        Ваше имя не будет раскрыто без вашего согласия.
        
        ---

  - type: input
    id: violation-url
    attributes:
      label: 🔗 URL источника нарушения
      description: Ссылка на курс, канал, пост или другой источник
      placeholder: "https://example.com/course или https://t.me/channel/post123"
    validations:
      required: true

  - type: dropdown
    id: violation-type
    attributes:
      label: 📋 Тип нарушения
      multiple: true
      options:
        - "💰 Продажа курса/вебинара с нашими материалами"
        - "📱 Размещение в платном Telegram-канале"
        - "🔐 Закрытый платный клуб/подписка"
        - "👤 Присвоение авторства (выдают за своё)"
        - "🏷️ Удаление лицензионного header"
        - "📝 Копирование из руководства без атрибуции"
        - "🎯 Обнаружен honeypot промпт (fingerprint case)"
        - "🔄 Нарушение Share-Alike (модифицировали, не поделились)"
        - "🤔 Не уверен(-а) — требуется анализ"
    validations:
      required: true

  - type: input
    id: source-file
    attributes:
      label: 📂 Файл из нашего репозитория (если известен)
      description: "Например: prompts/contracts/supply-contract.md"
      placeholder: "prompts/category/filename.md"

  - type: input
    id: fingerprint-id
    attributes:
      label: 🔍 Fingerprint ID (если видите в скопированном материале)
      description: "Например: LPH-2025-CONTRACTS-A7B3"
      placeholder: "LPH-2025-..."

  - type: textarea
    id: evidence
    attributes:
      label: 📸 Доказательства и описание
      description: |
        **Опишите, что именно скопировано или нарушено.**
        
        Примеры:
        - Цитата из промпта: "ООО Сердечный Тромб..."
        - Скопирована методология Метода Хирона
        - Совпадает структура: "4 модели мышления"
        
        **Прикрепите скриншоты:** используйте drag-and-drop ниже
      placeholder: |
        1. На слайде курса видно: "Анализируй договор между ООО Сердечный Тромб..."
        2. Это точный копипаст из нашего honeypot промпта
        3. Скриншот приложен ниже
        
        Дополнительный контекст:
        - Курс стоит 15 000 руб.
        - Опубликован 15.11.2025
        - Нет ссылки на Legal Prompts Hub
    validations:
      required: true

  - type: checkboxes
    id: commercial-use
    attributes:
      label: 💰 Контекст коммерческого использования
      options:
        - label: "Продаётся за деньги"
        - label: "Есть явная цена (курс, подписка)"
        - label: "Нет ссылки на Legal Prompts Hub (нарушение атрибуции)"
        - label: "Лицензионный header удалён или изменён"

  - type: textarea
    id: additional-context
    attributes:
      label: 📝 Дополнительная информация (опционально)
      description: Любые другие детали, которые могут помочь
      placeholder: |
        - Автор курса: Иван Иванов (@ivan_ivanov)
        - Дата публикации: 15.11.2025
        - Количество студентов: ~500
        - Платформа: Skillbox, Нетология и т.д.

  - type: checkboxes
    id: terms
    attributes:
      label: ✅ Подтверждение
      options:
        - label: "Я подтверждаю, что информация достоверна и добросовестна"
          required: true
        - label: "Я понимаю, что ложные обвинения недопустимы"
          required: true

  - type: markdown
    attributes:
      value: |
        ---
        
        ## Что дальше?
        
        ### Процесс обработки:
        
        1. ✅ **Мы подтвердим получение** (24-48 часов)
           - Вы получите комментарий в этом Issue
           - Нам может потребоваться уточнить детали
        
        2. 🔍 **Проведём расследование** (3-5 дней)
           - Сравним с нашим репозиторием
           - Проверим fingerprint cases
           - Сохраним скриншоты в Wayback Machine
        
        3. 📨 **Отправим требование** (если нарушение подтверждено)
           - Письмо нарушителю с требованием убрать материалы
           - Срок: 14 дней
           - Предложение легализации (добавить атрибуцию)
        
        4. ⚖️ **Эскалация** (если проигнорировано)
           - Публикация в [Hall of Shame](../../community/hall-of-shame.md)
           - Уведомление образовательных платформ
           - Публичное порицание
        
        5. ✅ **Разрешение** (если исправлено)
           - Нарушитель исправил ситуацию
           - Удаление из Hall of Shame
           - Благодарность в CONTRIBUTORS.md
        
        ### Гарантии:
        
        ✅ **Анонимность:** Ваше имя не раскроется  
        ✅ **Прозрачность:** Все этапы задокументированы  
        ✅ **Справедливость:** Нарушителю дается шанс исправиться  
        ✅ **Публичность:** Результаты видны сообществу  
        
        ---
        
        **Спасибо за помощь в развитии честного Open Source!** 🙏
